#!/usr/bin/env python3
"""Render LaTeX tables for the paper from JSON stats."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


PAPER_DIR = Path(__file__).resolve().parents[1]
GENERATED_DIR = PAPER_DIR / "generated"


def _tex_escape(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(ch, ch) for ch in text)


def _fmt_int(value: Any) -> str:
    if value is None:
        return "0"
    try:
        return str(int(value))
    except Exception:  # noqa: BLE001
        return "0"


def _fmt_ms(value: Any) -> str:
    if value is None:
        return "--"
    try:
        return f"{float(value):.3f}"
    except Exception:  # noqa: BLE001
        return "--"


def _fmt_eps(value: Any) -> str:
    if value is None:
        return "--"
    try:
        v = float(value)
        if v >= 1e6:
            return f"{v/1e6:.2f}M"
        if v >= 1e3:
            return f"{v/1e3:.2f}k"
        return f"{v:.2f}"
    except Exception:  # noqa: BLE001
        return "--"


def render_case_study_table(case_stats: list[dict[str, Any]]) -> str:
    rows: list[str] = []
    for entry in case_stats:
        label = entry.get("label", entry.get("study_id", ""))
        status = entry.get("status", "skipped")
        if status != "ok":
            rows.append(
                "    "
                + " & ".join(
                    [
                        _tex_escape(str(label)),
                        "--",
                        "--",
                        "--",
                        "--",
                        "--",
                        "--",
                        "--",
                        "--",
                        "--",
                        "--",
                        "--",
                        "--",
                    ]
                )
                + r" \\"
            )
            continue

        graph = entry.get("graph", {})
        nk = graph.get("node_kind_counts", {})
        ek = graph.get("edge_kind_counts", {})

        row = [
            _tex_escape(str(label)),
            _fmt_int(graph.get("nodes")),
            _fmt_int(graph.get("edges")),
            _fmt_int(nk.get("tool", 0)),
            _fmt_int(nk.get("llm", 0)),
            _fmt_int(nk.get("router", 0)),
            _fmt_int(nk.get("human", 0)),
            _fmt_int(nk.get("subgraph", 0)),
            _fmt_int(ek.get("direct", 0)),
            _fmt_int(ek.get("conditional", 0)),
            _fmt_int(ek.get("parallel", 0)),
            _fmt_int(ek.get("loop", 0)),
            _fmt_ms(entry.get("extract_median_ms")),
        ]
        rows.append("    " + " & ".join(row) + r" \\")

    body = "\n".join(rows) if rows else r"    (no data) \\"
    return "\n".join(
        [
            "% Auto-generated by scripts/render_tables.py",
            r"\begin{table}[t]",
            r"  \centering",
            r"  \scriptsize",
            r"  \caption{Graph statistics and extractor runtimes for representative workflows. Node-kind columns report counts of TOOL/LLM/ROUTER/HUMAN/SUBGRAPH nodes; other kinds (ENTRY/EXIT/PASSTHROUGH) are included in $|V|$.}",
            r"  \label{tab:case-studies}",
            r"  \resizebox{\linewidth}{!}{%",
            r"  \begin{tabular}{lrrrrrrrrrrrr}",
            r"    \toprule",
            r"    Study & $|V|$ & $|E|$ & Tool & LLM & Router & Human & Subg & Dir & Cond & Par & Loop & Med.\ ms \\",
            r"    \midrule",
            body,
            r"    \bottomrule",
            r"  \end{tabular}",
            r"  }",
            r"\end{table}",
            "",
        ]
    )


def render_case_study_verification_table(case_stats: list[dict[str, Any]]) -> str:
    rows: list[str] = []
    trace_cols = ["happy_path", "forbidden_tool", "policy_violation"]

    for entry in case_stats:
        label = entry.get("label", entry.get("study_id", ""))
        status = entry.get("status", "skipped")
        if status != "ok":
            rows.append(
                "    "
                + " & ".join(
                    [
                        _tex_escape(str(label)),
                        "--",
                        "--",
                        "--",
                        "--",
                    ]
                )
                + r" \\"
            )
            continue

        verification = entry.get("verification", {}) or {}
        structural = verification.get("structural", {}) or {}
        temporal = verification.get("temporal", {}) or {}

        struct_cell = "--"
        try:
            struct_cell = f"{int(structural.get('passed_count', 0))}/{int(structural.get('total', 0))}"
        except Exception:  # noqa: BLE001
            struct_cell = "--"

        trace_statuses: list[str] = []
        traces = temporal.get("traces", {}) or {}
        for trace_id in trace_cols:
            t = traces.get(trace_id, {}) or {}
            trace_statuses.append(_tex_escape(str(t.get("status", "--"))))

        row = [
            _tex_escape(str(label)),
            _tex_escape(struct_cell),
            *trace_statuses,
        ]
        rows.append("    " + " & ".join(row) + r" \\")

    body = "\n".join(rows) if rows else r"    (no data) \\"
    return "\n".join(
        [
            "% Auto-generated by scripts/render_tables.py",
            r"\begin{table}[t]",
            r"  \centering",
            r"  \small",
            r"  \caption{Structural check results and temporal monitor outcomes over representative traces (one safe and two unsafe) for each case study.}",
            r"  \label{tab:case-study-verification}",
            r"  \begin{tabular}{lrrrr}",
            r"    \toprule",
            r"    Study & Struct.\ (pass/total) & happy\_path & forbidden\_tool & policy\_violation \\",
            r"    \midrule",
            body,
            r"    \bottomrule",
            r"  \end{tabular}",
            r"\end{table}",
            "",
        ]
    )


def render_bench_table(bench_stats: dict[str, Any]) -> str:
    compile_rows = bench_stats.get("compile", []) or []
    evaluate = bench_stats.get("evaluate", {}) or {}

    rows: list[str] = []
    for r in compile_rows:
        rows.append(
            "    "
            + " & ".join(
                [
                    _tex_escape(str(r.get("rule_id", ""))),
                    r"\texttt{" + _tex_escape(str(r.get("dsl", ""))) + "}",
                    _fmt_int(r.get("predicate_count")),
                    _fmt_ms(r.get("compile_median_ms")),
                    "--",
                ]
            )
            + r" \\"
        )

    rows.append(r"    \midrule")
    rows.append(
        "    "
        + " & ".join(
            [
                "evaluate",
                _tex_escape(f"{evaluate.get('monitor_count', '--')} monitors on {evaluate.get('event_count', '--')} events"),
                _fmt_int(evaluate.get("monitor_count")),
                "--",
                _fmt_eps(evaluate.get("median_events_per_sec")),
            ]
        )
        + r" \\"
    )

    body = "\n".join(rows) if rows else r"    (no data) \\"
    return "\n".join(
        [
            "% Auto-generated by scripts/render_tables.py",
            r"\begin{table}[t]",
            r"  \centering",
            r"  \small",
            r"  \caption{Temporal monitor microbenchmarks. Compile time is the median over 500 runs per DSL string. Evaluation throughput is measured on a fixed 1{,}000-event synthetic stream (median over 50 runs).}",
            r"  \label{tab:bench}",
            r"  \begin{tabular}{llrrr}",
            r"    \toprule",
            r"    ID & DSL / workload & Preds & Compile ms (median) & Eval events/s (median) \\",
            r"    \midrule",
            body,
            r"    \bottomrule",
            r"  \end{tabular}",
            r"\end{table}",
            "",
        ]
    )


def main() -> None:
    case_path = GENERATED_DIR / "case_study_stats.json"
    bench_path = GENERATED_DIR / "bench_stats.json"
    if not case_path.exists() or not bench_path.exists():
        raise SystemExit(
            "Missing JSON inputs.\n"
            "Run: python3 scripts/collect_case_study_stats.py"
        )

    case_stats = json.loads(case_path.read_text())
    bench_stats = json.loads(bench_path.read_text())

    (GENERATED_DIR / "case_study_table.tex").write_text(render_case_study_table(case_stats))
    (GENERATED_DIR / "case_study_verification_table.tex").write_text(render_case_study_verification_table(case_stats))
    (GENERATED_DIR / "bench_table.tex").write_text(render_bench_table(bench_stats))

    print(f"Wrote {GENERATED_DIR / 'case_study_table.tex'}")
    print(f"Wrote {GENERATED_DIR / 'case_study_verification_table.tex'}")
    print(f"Wrote {GENERATED_DIR / 'bench_table.tex'}")


if __name__ == "__main__":
    main()
