"""Static temporal verification via graph x DFA product construction.

Given an :class:`AgentGraph` and a :class:`CompiledMonitorRule`, this module
performs a BFS over the product of the graph's node space and the DFA state
space to check temporal policy compliance *statically* — without requiring a
runtime event trace.

Scope: FINITE MAXIMAL EXECUTIONS ONLY (LTLf)
--------------------------------------------
An execution is modeled as a finite path from the entry node to a
*termination point*. Termination points are:

* exit nodes (``graph.exit_ids``) — the execution *may* end there, and
* dead-end nodes (no successors, not in ``exit_ids``) — the execution
  *must* end there. Dead ends are treated as trace end for the LTLf
  unfulfilled-obligation check exactly like exits. (The pre-2026-07 code
  silently skipped the end-of-trace check at dead ends; that was a soundness
  hole and is now closed.)

This checker does NOT decide policies over infinite executions. A reachable
product cycle whose DFA state stays non-accepting is reported only as a
heuristic *inconclusive* signal (``divergent_obligation_possible``) — it is
never a violation verdict, because deciding infinite-run semantics correctly
would require generalized-Buchi acceptance, which this product does not
implement.

Multi-tool TOOL nodes (conservative resolution)
-----------------------------------------------
AST-level extraction cannot prove that a declared tool binding is actually
invoked, nor in what order, nor how many times. By default, a TOOL node with
declared tools ``T`` is therefore interpreted as emitting *any finite
sequence of invocations of tools in T, including the empty sequence*. This
is implemented as a DFA-state closure: from product state ``(v, q)`` the set
of post-node DFA states is the closure of ``{q}`` under the transition
symbols of each single-tool event of ``T``. If ANY state reached during the
closure (including intermediates) is a violation state, some resolution of
the node is a bad prefix (may-violation). Successors of ``v`` continue from
EVERY state in the closure. A TOOL node with NO declared tools is resolved
as any finite sequence — including the empty sequence — of the *bare
node-visit event* ``{"node_id": ..., "action_type": "tool"}`` (built by
:func:`node_visit_event`, the same constructor
:func:`agentproof.api._event_for_node` uses): nothing can be proven about
which tool such a node calls, but the runtime event model still records
every visit of it as a tool action.

Static/runtime event-model invariant
------------------------------------
For every node, the event set considered by the default static closure is a
SUPERSET of every event :func:`agentproof.api._event_for_node` can emit for
that node (both sides build events via :func:`node_visit_event`). Hence a
static ``"safe"`` verdict can never coexist with a runtime bad-prefix
violation on a trace generated by :func:`agentproof.api.generate_traces`
over the same graph.

Passing an explicit ``event_mapper`` opts out of this conservative
expansion: the caller asserts exact single events, one per node visit, and
the product uses them verbatim (the pre-expansion behavior).

Verdict semantics (see :func:`check_temporal_property`) are CONDITIONED on
the extracted graph being trace-conservative, i.e. its paths
over-approximate the workflow's runtime traces.
"""

from __future__ import annotations

from collections import deque
from typing import Any, Callable

from agentproof.graph.model import (
    AgentGraph,
    GraphNode,
    NodeKind,
    adjacency,
    node_by_id,
)
from agentproof.monitor.ltl import CompiledMonitorRule, _event_symbol


def node_visit_event(node: GraphNode, tool_name: str | None = None) -> dict[str, Any]:
    """Build the canonical event dict for a single visit of *node*.

    Single source of truth for the per-visit event shape, shared by the
    static closure in this module and by :func:`agentproof.api._event_for_node`
    (which selects *tool_name* per visit). This sharing is what upholds the
    static/runtime event-model invariant documented in the module docstring:
    the static side can only ever check events the runtime side can emit,
    and vice versa.

    For a TOOL node, ``tool_name`` names the declared tool bound on this
    visit; ``tool_name=None`` means the node declares no tools, yielding the
    bare visit event ``{"node_id": ..., "action_type": "tool"}`` (no
    ``tool_name``, no tags).
    """
    event: dict[str, Any] = {"node_id": node.id, "action_type": node.kind.value}
    if node.kind == NodeKind.TOOL and tool_name is not None:
        event["tool_name"] = tool_name
        event["tags"] = ["tool"]
    elif node.kind == NodeKind.LLM:
        event["tags"] = ["llm_step"]
    elif node.kind == NodeKind.HUMAN:
        event["tags"] = ["human"]
    elif node.kind == NodeKind.ROUTER:
        event["tags"] = ["router"]
    return event


def _default_event_mapper(node_id: str, graph: AgentGraph) -> dict[str, Any]:
    """Generate a single synthetic event dict for a graph node.

    Delegates to :func:`node_visit_event` (shared with
    ``agentproof.api._event_for_node``), binding ``tools[0]`` for TOOL
    nodes. The default verification path uses this only for non-TOOL nodes
    (TOOL nodes get the conservative closure expansion instead); when a
    caller passes an event mapper explicitly to
    :func:`check_temporal_property`, that mapper — including this one — is
    used verbatim for every node (caller-asserted exact events).
    """
    node = node_by_id(graph, node_id)
    if node is None:
        return {"node_id": node_id, "action_type": "unknown"}
    tool_name = node.tools[0] if node.kind == NodeKind.TOOL and node.tools else None
    return node_visit_event(node, tool_name)


def _witness_confidence(graph: AgentGraph, path: list[str] | None) -> str | None:
    """Provenance strength of a witness path.

    ``"exact"`` iff every edge traversed on the path has
    ``confidence == "exact"`` AND every TOOL node on the path (whose tool
    bindings determine the events the DFA saw) has ``confidence == "exact"``;
    otherwise ``"may"``. ``None`` when there is no path. Edges are looked up
    by ``(source, target)``; when parallel edges exist for a pair, ALL of
    them must be exact (the witness could have traversed any of them).
    Non-TOOL nodes' confidence is not consulted: only their edges and tool
    bindings affect the events checked. Attributes are read with ``getattr``
    defaults so legacy objects without provenance degrade to ``"may"``.
    """
    if not path:
        return None
    edge_conf: dict[tuple[str, str], str] = {}
    for e in graph.edges:
        key = (getattr(e, "source", ""), getattr(e, "target", ""))
        conf = getattr(e, "confidence", "may")
        prev = edge_conf.get(key)
        if prev is None or (prev == "exact" and conf != "exact"):
            edge_conf[key] = conf
    for a, b in zip(path, path[1:]):
        if edge_conf.get((a, b), "may") != "exact":
            return "may"
    for node_id in path:
        node = node_by_id(graph, node_id)
        if node is None:
            return "may"
        if node.kind == NodeKind.TOOL and getattr(node, "confidence", "may") != "exact":
            return "may"
    return "exact"


def check_temporal_property(
    graph: AgentGraph,
    rule: CompiledMonitorRule,
    event_mapper: Callable[[str, AgentGraph], dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Check a temporal property against a graph using product construction.

    The claim is restricted to FINITE MAXIMAL EXECUTIONS of the graph:
    paths from the entry node to a termination point (an exit node, or a
    dead-end node — no successors and not in ``exit_ids`` — which counts as
    trace end exactly like an exit). Infinite executions are out of scope;
    see ``inconclusive_reason`` below.

    Parameters
    ----------
    graph : AgentGraph
        The agent workflow graph to verify.
    rule : CompiledMonitorRule
        A compiled temporal monitor rule (from :mod:`agentproof.monitor.ltl`).
    event_mapper : callable, optional
        A function ``(node_id, graph) -> event_dict``. When omitted (the
        default), TOOL nodes are expanded conservatively: every finite
        sequence of invocations of the node's declared tools, including the
        empty sequence, is considered (DFA-state closure); a TOOL node with
        no declared tools is expanded over its bare visit event
        ``{"node_id": ..., "action_type": "tool"}`` the same way. When
        passed explicitly, the mapper's single event per node is used
        verbatim — the caller thereby asserts the events are exact.

    Returns
    -------
    dict
        A JSON-serializable result containing:

        - ``rule_id``: the rule identifier
        - ``verdict``: ``"safe"`` | ``"may_violate"`` | ``"inconclusive"``.
          ``"safe"`` means NO resolution of the may-graph's finite maximal
          executions violates the policy, CONDITIONED on the extracted graph
          being trace-conservative (its paths over-approximate runtime
          traces). ``"may_violate"`` means some resolution violates it.
          ``"inconclusive"`` means the finite-trace checker cannot certify
          the graph (see ``inconclusive_reason``).
        - ``violated``: bool, exactly ``verdict == "may_violate"``
        - ``violation_kind``: ``"bad_prefix"`` (a reachable resolution
          drives the DFA into a violation state) or
          ``"unfulfilled_obligation"`` (a resolution can terminate — at an
          exit node or a dead end — while the DFA is non-accepting), or
          ``None`` when ``verdict != "may_violate"``
        - ``violation_path``: list of node IDs of the may-witness leading to
          the violation, or ``None``
        - ``witness_confidence``: ``"exact"`` if every edge traversed on the
          witness path has ``confidence == "exact"`` and every TOOL node on
          it has exact tool bindings, else ``"may"``; ``None`` when there is
          no witness
        - ``inconclusive_reason``: ``"divergent_obligation_possible"`` when
          the only finding is a reachable product cycle whose DFA state
          stays non-accepting (a heuristic signal that an infinite run could
          postpone an obligation forever — undecided here, since infinite
          runs are out of scope); ``"no_exit_reachable"`` when no
          termination point (exit node or dead end) is reachable at all, so
          no finite maximal execution exists to certify; else ``None``
        - ``divergence_witness``: node-ID path to a product state on (or
          leading to) the non-accepting cycle, when
          ``inconclusive_reason == "divergent_obligation_possible"``; else
          ``None``
        - ``graph_warnings``: verdict-independent list of strings flagging
          malformed-graph conditions; contains
          ``"duplicate_node_ids: [...]"`` when several nodes share an id
          (the FIRST occurrence wins everywhere, consistent with
          ``graph.model.node_by_id``), empty list otherwise
        - ``product_states_explored``: number of ``(node, dfa_state)`` pairs
          explored during BFS
    """
    caller_asserted = event_mapper is not None
    mapper = event_mapper if event_mapper is not None else _default_event_mapper

    adj = adjacency(graph)
    exit_ids = set(graph.exit_ids)
    # First occurrence wins on duplicate ids, consistent with
    # graph.model.node_by_id (used by _default_event_mapper,
    # _witness_confidence, and api._event_for_node). Duplicates are
    # surfaced as verdict-independent metadata in ``graph_warnings``.
    nodes_by_id: dict[str, GraphNode] = {}
    duplicate_ids: list[str] = []
    for n in graph.nodes:
        if n.id in nodes_by_id:
            if n.id not in duplicate_ids:
                duplicate_ids.append(n.id)
        else:
            nodes_by_id[n.id] = n
    graph_warnings: list[str] = []
    if duplicate_ids:
        graph_warnings.append(f"duplicate_node_ids: {sorted(duplicate_ids)}")
    accepting = rule.accepting_states
    violating = rule.violation_states
    table = rule.transition_table

    # Per-node DFA symbols of the per-visit events, for the closure. Events
    # are built with node_visit_event, keeping the symbol set a superset of
    # everything api._event_for_node can emit for the node (see module
    # docstring invariant).
    tool_symbols_cache: dict[str, tuple[int, ...]] = {}

    def _tool_symbols(node: GraphNode) -> tuple[int, ...]:
        cached = tool_symbols_cache.get(node.id)
        if cached is None:
            if node.tools:
                events = [node_visit_event(node, tool) for tool in node.tools]
            else:
                # No declared tools: api._event_for_node still emits the
                # bare visit event {'node_id', 'action_type': 'tool'} on
                # every visit of this node, so the closure must cover
                # finite sequences of it (plus the empty sequence).
                events = [node_visit_event(node, None)]
            cached = tuple(_event_symbol(rule.predicates, e) for e in events)
            tool_symbols_cache[node.id] = cached
        return cached

    def _post_states(v: str, q: int) -> tuple[list[int], bool]:
        """DFA states possible after processing node *v* from state *q*.

        Returns ``(sorted post-state list, bad_prefix_hit)``. The hit flag
        is True when any state reached while processing the node —
        including intermediate closure states — is a violation state.
        """
        row = table.get(q)
        if row is None:
            # Malformed rule: no transitions from here; the resolution set
            # is empty and nothing can be concluded through this state.
            return [], False
        node = nodes_by_id.get(v)
        if not caller_asserted and node is not None and node.kind == NodeKind.TOOL:
            # Conservative resolution of a TOOL node: any finite sequence
            # of invocations of its declared tools, INCLUDING the empty
            # sequence => closure of {q} under each single-tool symbol.
            # With no declared tools the closure runs over the bare
            # node-visit event instead (see _tool_symbols).
            symbols = _tool_symbols(node)
            closure = {q}
            frontier = [q]
            while frontier:
                state = frontier.pop()
                state_row = table.get(state)
                if state_row is None:
                    continue
                for sym in symbols:
                    nxt = state_row[sym]
                    if nxt not in closure:
                        closure.add(nxt)
                        frontier.append(nxt)
            hit = any(s in violating for s in closure)
            return sorted(closure), hit
        event = mapper(v, graph)
        q_prime = row[_event_symbol(rule.predicates, event)]
        return [q_prime], q_prime in violating

    # BFS over product states (node_id, dfa_state_before_processing_node)
    initial_product = (graph.entry_id, rule.initial_state)
    queue: deque[tuple[str, int]] = deque([initial_product])
    visited: set[tuple[str, int]] = {initial_product}
    parent: dict[tuple[str, int], tuple[str, int] | None] = {initial_product: None}
    # Successor product states reachable via a NON-ACCEPTING post state,
    # for the divergence (non-accepting product cycle) heuristic: an edge
    # (v, q) -> (u, p) with p non-accepting means some resolution of v
    # leaves the DFA non-accepting when the run moves on to u.
    pending_succ: dict[tuple[str, int], list[tuple[str, int]]] = {}

    violation_product_state: tuple[str, int] | None = None
    violation_kind: str | None = None
    termination_reachable = False

    while queue:
        v, q = queue.popleft()

        posts, hit = _post_states(v, q)
        if hit:
            violation_product_state = (v, q)
            violation_kind = "bad_prefix"
            break

        succ_nodes = adj.get(v) or []

        # LTLf end-of-trace check at termination points: exit nodes (the
        # execution MAY end) and dead ends (it MUST end). A resolution that
        # terminates here with a non-accepting DFA state carries an
        # unfulfilled obligation.
        if v in exit_ids or not succ_nodes:
            termination_reachable = True
            if any(p not in accepting for p in posts):
                violation_product_state = (v, q)
                violation_kind = "unfulfilled_obligation"
                break

        pend: list[tuple[str, int]] = []
        for u in succ_nodes:
            for p in posts:
                product_next = (u, p)
                if p not in accepting:
                    pend.append(product_next)
                if product_next not in visited:
                    visited.add(product_next)
                    parent[product_next] = (v, q)
                    queue.append(product_next)
        pending_succ[(v, q)] = pend

    def _path_to(state: tuple[str, int]) -> list[str]:
        path_nodes: list[str] = []
        current: tuple[str, int] | None = state
        while current is not None:
            path_nodes.append(current[0])
            current = parent.get(current)
        path_nodes.reverse()
        return path_nodes

    result: dict[str, Any] = {
        "rule_id": rule.rule_id,
        "verdict": "safe",
        "violated": False,
        "violation_kind": None,
        "violation_path": None,
        "witness_confidence": None,
        "inconclusive_reason": None,
        "divergence_witness": None,
        "graph_warnings": graph_warnings,
        "product_states_explored": len(visited),
    }

    if violation_product_state is not None:
        path = _path_to(violation_product_state)
        result["verdict"] = "may_violate"
        result["violated"] = True
        result["violation_kind"] = violation_kind
        result["violation_path"] = path
        result["witness_confidence"] = _witness_confidence(graph, path)
        return result

    # Divergence heuristic (downgraded from a violation verdict): find a
    # reachable product cycle every step of which leaves the DFA
    # non-accepting. Greatest fixpoint: keep states with some pending
    # successor that itself survives; anything left lies on or leads to a
    # non-accepting cycle. This witnesses only an INFINITE run postponing
    # an obligation forever — out of the finite-trace scope, hence
    # inconclusive rather than violated.
    core = {s for s, pend in pending_succ.items() if pend}
    changed = True
    while changed:
        changed = False
        for s in list(core):
            if not any(t in core for t in pending_succ.get(s, [])):
                core.discard(s)
                changed = True
    if core:
        witness_state = min(core)  # deterministic witness
        result["verdict"] = "inconclusive"
        result["inconclusive_reason"] = "divergent_obligation_possible"
        result["divergence_witness"] = _path_to(witness_state)
        return result

    if not termination_reachable:
        # Every reachable node has successors and none is an exit: all
        # maximal executions are infinite, so there is no finite maximal
        # run for this checker to certify.
        result["verdict"] = "inconclusive"
        result["inconclusive_reason"] = "no_exit_reachable"
        return result

    return result
